import { FigmaEmbed } from './embeds/FigmaEmbed';
import type { Project } from '../data/projects';
import type { BlueprintSection } from './CaseStudyBlueprint';
import lumnPreview from '../../assets/images/Lumn.jpg';
import lumnMobile from '../../assets/images/LUMN_mobile.jpg';

const FIGMA_FILE_URL =
  'https://www.figma.com/design/fYwhBS4WdU21aEjBQKEGVl/Julio-Coraspe-Lumn?node-id=0-1';

// Each section of the Figma file, addressed by node id so the embed opens on
// the relevant artboards instead of the whole canvas.
const figmaEmbed = (nodeId: string) =>
  `https://embed.figma.com/design/fYwhBS4WdU21aEjBQKEGVl/Julio-Coraspe-Lumn?node-id=${nodeId}&embed-host=share`;

const BRAND_EMBED = figmaEmbed('189-874');
const DIRECTIONS_EMBED = figmaEmbed('189-873');
const SCREENS_EMBED = figmaEmbed('169-601');

const MOTION_STUDY_URL = 'https://juliocoraspe.github.io/birdsong-viz/';
const MOTION_STUDY_REPO = 'https://github.com/juliocoraspe/birdsong-viz';

// How the audio analysis drives the geometry. Taken from the study's own
// mapping spec rather than described loosely.
const AUDIO_MAPPING: { channel: string; source: string }[] = [
  { channel: 'X axis', source: 'Frequency, 0–10 kHz' },
  { channel: 'Y axis', source: 'Amplitude, per frequency bin' },
  { channel: 'Z axis', source: 'Time — a trailing history of 120 frames' },
  { channel: 'Colour', source: 'Spectral flatness, or an MFCC-derived palette' },
  { channel: 'Scale', source: 'RMS — overall loudness' },
];

export function getLumnBlueprintSections(project: Project): BlueprintSection[] {
  return [
    {
      id: '01',
      label: 'Context',
      body: (
        <>
          <p>{project.context}</p>
          <p>
            The sequence matters here: brand before screens. Because the product&apos;s job is to
            lower sensory load, deciding what the interface should feel like had to happen before
            deciding what it should contain — otherwise the layout would set the emotional register
            by accident.
          </p>

          <ol className="dp-context-timeline" aria-label="LUMN project process">
            <li><span>01</span><strong>Mood</strong><small>Imagery and tone establishing an emotional baseline</small></li>
            <li><span>02</span><strong>Brand</strong><small>Logo, voice, and the multi-sensory premise</small></li>
            <li><span>03</span><strong>Structure</strong><small>Lo-fi layouts prioritizing spatial calm</small></li>
            <li><span>04</span><strong>Diverge</strong><small>Two contrasting creative directions, fully built out</small></li>
            <li><span>05</span><strong>Systematize</strong><small>Type, colour, spacing, and motion principles</small></li>
            <li><span>06</span><strong>Explore</strong><small>Coded motion study for the Display screen</small></li>
          </ol>

          <p className="cs-bp-muted">
            Role: {project.role} · Timeline: 2025
          </p>
        </>
      ),
    },
    {
      id: '02',
      label: 'Problem',
      body: (
        <>
          <p>{project.problem}</p>
          <p>
            Stated as a design problem, it inverts the usual brief: most interfaces compete for
            attention, and here the interface has to actively decline it. Every decision that would
            normally be evaluated on engagement — contrast, motion, density, colour — has to be
            evaluated on whether it lets the sound stay in the foreground.
          </p>
          <p className="cs-bp-muted">
            How might an ASMR interface remain present and controllable while contributing as little
            perceptual load as possible, so attention stays with the audio rather than the screen?
          </p>
        </>
      ),
    },
    {
      id: '03',
      label: 'Brand Foundation',
      body: (
        <>
          <p>
            LUMN was framed as a response to the sensory overwhelm it is meant to relieve. The
            premise is a dialogue between three channels: generative visuals built with Three.js that
            react to sound in real time, ASMR audio generated by AI models, and a haptic layer whose
            intensity the listener sets. None of the three is meant to dominate — the environment
            adapts to each person&apos;s sensitivity rather than imposing one intensity on everyone.
          </p>
          <p>
            That premise produced the brand work before any screen existed: a moodboard to fix the
            emotional register, then a logo and identity resolved in both a light and a dark
            treatment, since the direction question was still open at that point.
          </p>

          <div className="cs-bp-media cs-bp-media-landscape" style={{ height: 280, maxWidth: '100%' }}>
            <div className="cs-bp-media-frame">
              <FigmaEmbed
                title="LUMN brand identity, logos, and animation studies"
                src={BRAND_EMBED}
                wrapperClassName="cs-bp-media-fill"
                iframeClassName="cs-bp-media-fill"
                buttonLabel="Load brand identity"
                mobileStaticImageSrc={lumnPreview}
                mobileStaticImageAlt="LUMN brand identity preview"
                mobileLinkHref={FIGMA_FILE_URL}
                mobileLinkLabel="Open Figma Design"
              />
            </div>
          </div>

          <p className="cs-bp-muted dp-synthesis-artifact__insight">
            Design implication: if the brand promises adaptation rather than stimulation, the
            interface cannot carry a fixed emotional charge — which is what the next decision had to
            resolve.
          </p>
        </>
      ),
    },
    {
      id: '04',
      label: 'Creative Directions',
      body: (
        <>
          <p>
            Rather than iterating toward one look, two opposed directions were built out in full —
            each with its own home, menu, display, settings, and profile screens — so the choice
            could be made on evidence rather than preference.
          </p>

          <div className="dp-research-methods" aria-label="The two creative directions explored">
            <article>
              <span>Direction 01</span>
              <h5>Dark and expressive</h5>
              <p>
                Neon accents against deep backgrounds, high contrast, a cosmic register. Visually
                striking and the more distinctive of the two — but the visuals hold attention, and
                every accent reads as an event worth looking at.
              </p>
            </article>
            <article>
              <span>Direction 02</span>
              <h5>Reduced and light</h5>
              <p>
                Soft whites, muted blacks, visual stillness. Less immediately impressive in a
                portfolio thumbnail, but it recedes — which is the entire requirement.
              </p>
            </article>
          </div>

          <p style={{ margin: '16px 0 12px' }}>
            Direction 02 was selected. The reasoning is the problem statement applied literally: the
            dark direction was the better <em>image</em> and the worse <em>instrument</em>. Its
            contrast and neon accents competed with the sound-reactive visuals on the Display screen,
            which meant the one element that genuinely needed to move was fighting a background that
            was already moving. The light direction leaves that channel free.
          </p>

          <div className="cs-bp-media cs-bp-media-landscape" style={{ height: 280, maxWidth: '100%' }}>
            <div className="cs-bp-media-frame">
              <FigmaEmbed
                title="LUMN creative directions — both explorations side by side"
                src={DIRECTIONS_EMBED}
                wrapperClassName="cs-bp-media-fill"
                iframeClassName="cs-bp-media-fill"
                buttonLabel="Load both creative directions"
                mobileStaticImageSrc={lumnMobile}
                mobileStaticImageAlt="LUMN creative directions preview"
                mobileLinkHref={FIGMA_FILE_URL}
                mobileLinkLabel="Open Figma Design"
              />
            </div>
          </div>
        </>
      ),
    },
    {
      id: '05',
      label: 'Design System & Screens',
      body: (
        <>
          <p>{project.solution}</p>
          <p style={{ margin: '16px 0 12px' }}>
            Restraint only reads as intentional if it is systematic, so the chosen direction was
            resolved into explicit rules before the screens were finalized.
          </p>

          <div className="dp-research-methods" aria-label="Design system rules">
            <article>
              <span>Spacing</span>
              <h5>8-point grid</h5>
              <p>
                All spacing derives from an 8-point base, so consistency is structural rather than
                eyeballed per screen.
              </p>
            </article>
            <article>
              <span>Contrast</span>
              <h5>Legible in both treatments</h5>
              <p>
                Type-to-background contrast meets legibility standards in the light and the dark
                direction alike — restraint was never allowed to become low contrast.
              </p>
            </article>
            <article>
              <span>Hierarchy</span>
              <h5>Perception order made explicit</h5>
              <p>
                The typographic scale signals which element should be read first, so the eye is
                guided without needing colour or weight to shout.
              </p>
            </article>
            <article>
              <span>Comprehension</span>
              <h5>A purpose line per screen</h5>
              <p>
                Each screen carries a short description of what it is for, reducing cognitive load
                instead of relying on the user to infer the model.
              </p>
            </article>
          </div>

          <p style={{ margin: '16px 0 12px' }}>
            Text sizes, component spacing, and alignment follow accessible design principles that
            support comfortable reading and immediate interpretation for people with varying visual
            needs. The final screens below apply all of it.
          </p>

          <div className="cs-bp-media cs-bp-media-landscape" style={{ height: 280, maxWidth: '100%' }}>
            <div className="cs-bp-media-frame">
              <FigmaEmbed
                title="LUMN final screens"
                src={SCREENS_EMBED}
                wrapperClassName="cs-bp-media-fill"
                iframeClassName="cs-bp-media-fill"
                buttonLabel="Load final screens"
                mobileStaticImageSrc={lumnMobile}
                mobileStaticImageAlt="LUMN final screens preview"
                mobileLinkHref={FIGMA_FILE_URL}
                mobileLinkLabel="Open Figma Design"
              />
            </div>
          </div>

          <div className="cs-bp-vsplit-cta" style={{ marginTop: 14 }}>
            <a className="cs-bp-cta" href={FIGMA_FILE_URL} target="_blank" rel="noopener noreferrer">
              View the design file in Figma
              <span className="cs-bp-cta-arrow" aria-hidden="true">→</span>
            </a>
          </div>
        </>
      ),
    },
    {
      id: '06',
      label: 'Motion Study: Display Screen',
      layout: 'vsplit',
      body: (
        <div className="cs-bp-vsplit">
          <div className="cs-bp-vsplit-text">
            <div className="cs-bp-vsplit-title-row">
              <span className="cs-bp-display-num" aria-hidden="true">06</span>
              <h4 className="cs-bp-display-title">Motion Study: Display Screen</h4>
            </div>
            <div className="cs-bp-vsplit-body">
              <p>
                This is not a prototype of the app — it is a coded exploration of one screen. The
                Display screen&apos;s whole premise is a form that responds to what you are hearing,
                and that claim cannot be evaluated in a static mockup. So it was built.
              </p>
              <p>
                Three.js renders the geometry; Meyda and the Web Audio API analyse live microphone or
                file input at an FFT size of 2048. Each audio feature drives one visual property:
              </p>
              <ol className="rl-validation-flow" aria-label="How audio features map to visual properties">
                {AUDIO_MAPPING.map((m, i) => (
                  <li key={m.channel}>
                    <span>{String(i + 1).padStart(2, '0')}</span>
                    <strong>{m.channel}</strong>
                    <small>{m.source}</small>
                  </li>
                ))}
              </ol>
              <p>
                Three presets — cloudfield, nebula, and wirebloom — test how far the form can vary
                before it stops feeling calm. That threshold is the actual finding: reactivity reads
                as presence up to a point, and past it, it reads as another thing demanding
                attention.
              </p>
            </div>
            <div className="cs-bp-vsplit-cta">
              <a className="cs-bp-cta" href={MOTION_STUDY_REPO} target="_blank" rel="noopener noreferrer">
                See full code on GitHub
                <span className="cs-bp-cta-arrow" aria-hidden="true">→</span>
              </a>
            </div>
          </div>
          <div
            className="cs-bp-vsplit-media"
            style={{ ['--media-aspect' as string]: '390 / 844' }}
          >
            <div
              className="cs-bp-vsplit-media-frame"
              style={{
                ['--frame-w' as string]: '640px',
                ['--frame-h' as string]: '1385px',
                ['--frame-scale' as string]: '0.354',
              }}
            >
              <FigmaEmbed
                title={`${project.title} sound-reactive motion study`}
                src={MOTION_STUDY_URL}
                wrapperClassName="cs-bp-vsplit-frame border-0 no-scrollbar"
                iframeClassName="cs-bp-vsplit-frame border-0 no-scrollbar"
                loading="lazy"
                allow="fullscreen; autoplay; microphone; camera"
                allowFullScreen
                mobileStaticImageSrc={lumnPreview}
                mobileStaticImageAlt={`${project.title} motion study preview`}
                mobileStaticImageObjectFit="cover"
                mobileLinkHref={MOTION_STUDY_REPO}
                mobileLinkLabel="See full code on GitHub"
              />
            </div>
          </div>
        </div>
      ),
    },
    {
      id: '07',
      label: 'Outcome & Next Steps',
      body: (
        <>
          <ul>
            <li>{project.outcome[0]}</li>
            <li>{project.outcome[1]}</li>
            <li>{project.outcome[4]}</li>
          </ul>

          <p style={{ margin: '16px 0 12px' }}>
            The most useful result was structural rather than visual: committing to two full
            directions instead of one made the selection defensible. &ldquo;The light one recedes and
            the dark one competes&rdquo; is an argument; &ldquo;the light one feels calmer&rdquo;
            would only have been a preference.
          </p>

          <p className="rl-outcome-next-signal">
            Scope of this work: LUMN is an interface and motion exploration, not a validated product.
            No usability testing was run, the AI-generated audio layer was specified but not built,
            and the haptic system exists as a design decision rather than an implementation. The
            motion study proves the visual response is achievable in a browser — it does not prove it
            is relaxing. Next steps, in order: test the Display screen with listeners against a
            static control to find where reactivity stops reading as calm, implement the haptic
            intensity control on a real device, and bring the audio layer up from specification to a
            working prototype so the three channels can finally be evaluated together rather than
            separately.
          </p>
        </>
      ),
    },
  ];
}
